# Generated by Django 5.1.6 on 2025-02-08 08:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('table_number', models.IntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'В ожидании'),
                            ('ready', 'Готово'),
                            ('paid', 'Оплачено'),
                        ],
                        default='pending',
                        max_length=10,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'total_price',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.PositiveIntegerField(default=1)),
                (
                    'menu_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='orders.menuitem',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='orders.order',
                    ),
                ),
            ],
        ),
    ]
